name: CI

on:
  push:
    branches: [ main, development, release ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install -r requirements.txt

      - name: Run pytest
        run: export PYTHONPATH=$PYTHONPATH:$(pwd)/src && pytest -v

  build-docs:
    name: Build docs (mkdocs)
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install mkdocs
        run: pip install mkdocs

      - name: Build site
        run: mkdocs build --clean
      - name: Upload docs artifact (for inspection)
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site
